-- HOSTEL module tables
CREATE TABLE HOSTEL (
  HOSTEL_ID           NUMBER(19) PRIMARY KEY,
  OWNER_USER_ID       NUMBER(19) NOT NULL,
  HOSTEL_NAME         VARCHAR2(120) NOT NULL,
  GST_NUMBER          VARCHAR2(20),
  ADDRESS_LINE1       VARCHAR2(200) NOT NULL,
  ADDRESS_LINE2       VARCHAR2(200),
  AREA_LOCALITY       VARCHAR2(120),
  CITY_NAME           VARCHAR2(60) NOT NULL,
  STATE_NAME          VARCHAR2(60) NOT NULL,
  PINCODE             VARCHAR2(10),
  COUNTRY_NAME        VARCHAR2(60) DEFAULT 'India' NOT NULL,
  FLOORS_COUNT        NUMBER(3) NOT NULL,
  WHY_CHOOSE          VARCHAR2(2000),
  CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_HOSTEL_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_HOSTEL_OWNER ON HOSTEL(OWNER_USER_ID);
CREATE SEQUENCE HOSTEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HOSTEL_FLOOR_PLAN (
  FLOOR_PLAN_ID       NUMBER(19) PRIMARY KEY,
  HOSTEL_ID           NUMBER(19) NOT NULL,
  FLOOR_NUMBER        NUMBER(3) NOT NULL,
  ROOMS_COUNT         NUMBER(5) NOT NULL,
  CONSTRAINT FK_FLOOR_HOSTEL FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL(HOSTEL_ID) ON DELETE CASCADE,
  CONSTRAINT UK_FLOOR_UNIQUE UNIQUE (HOSTEL_ID, FLOOR_NUMBER)
);

CREATE SEQUENCE HOSTEL_FLOOR_PLAN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE FACILITY_MASTER (
  FACILITY_ID         NUMBER(19) PRIMARY KEY,
  FACILITY_NAME       VARCHAR2(60) NOT NULL,
  IS_ACTIVE           CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
  CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UK_FACILITY_NAME UNIQUE (FACILITY_NAME)
);

CREATE SEQUENCE FACILITY_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HOSTEL_FACILITY_MAP (
  HOSTEL_ID           NUMBER(19) NOT NULL,
  FACILITY_ID         NUMBER(19) NOT NULL,
  PRIMARY KEY (HOSTEL_ID, FACILITY_ID),
  CONSTRAINT FK_MAP_HOSTEL FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL(HOSTEL_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MAP_FACILITY FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY_MASTER(FACILITY_ID)
);

CREATE INDEX IDX_HOSTEL_FACILITY_HOSTEL ON HOSTEL_FACILITY_MAP(HOSTEL_ID);
CREATE INDEX IDX_HOSTEL_FACILITY_FAC ON HOSTEL_FACILITY_MAP(FACILITY_ID);

INSERT INTO FACILITY_MASTER (FACILITY_ID, FACILITY_NAME) VALUES (FACILITY_MASTER_SEQ.NEXTVAL, 'WiFi');
INSERT INTO FACILITY_MASTER (FACILITY_ID, FACILITY_NAME) VALUES (FACILITY_MASTER_SEQ.NEXTVAL, 'Laundry');
INSERT INTO FACILITY_MASTER (FACILITY_ID, FACILITY_NAME) VALUES (FACILITY_MASTER_SEQ.NEXTVAL, 'Meals');
INSERT INTO FACILITY_MASTER (FACILITY_ID, FACILITY_NAME) VALUES (FACILITY_MASTER_SEQ.NEXTVAL, 'CCTV');
INSERT INTO FACILITY_MASTER (FACILITY_ID, FACILITY_NAME) VALUES (FACILITY_MASTER_SEQ.NEXTVAL, 'Housekeeping');
COMMIT;
